from enum import Enum

class ResponseSignal(Enum):
    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_VALIDATION_FAILED_FILE_SIZE = "FILE_VALIDATION_FAILED_FILE_SIZE"
    FILE_VALIDATION_FAILED_FILE_TYPE = "FILE_VALIDATION_FAILED_FILE_TYPE"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"