from enum import Enum

class ResponseSignal(Enum):
    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_VALIDATION_FAILED_FILE_SIZE = "FILE_VALIDATION_FAILED_FILE_SIZE"
    FILE_VALIDATION_FAILED_FILE_TYPE = "FILE_VALIDATION_FAILED_FILE_TYPE"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_PROCESSING_SUCCESS = "FILE_PROCESSING_SUCCESS"
    FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED"
    FILE_PROCESSING_IN_PROGRESS = "FILE_PROCESSING_IN_PROGRESS"